## Documentation: http://docs.travis-ci.com/user/languages/julia/

notifications:
  email: false

language: julia

os:
  - linux
  - osx
#  - windows

julia:
  - 1.3

matrix:
  include:
    - os: linux
      julia: 1.1
    - os: linux
      julia: nightly

services:
  - postgresql
  - mysql

addons:
  apt:
    packages:
      - unixodbc
      - unixodbc-dev
      - odbc-postgresql

env:
  - POSTGRESQL_VERSION=9.6 PGHOST="/var/run/postgresql" ODBC_TEST_DRIVERS="postgresql"

before_install:
  - psql --version

before_script:
  # PostgreSQL - osx
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then rm -rf /usr/local/var/postgres                                                               ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then initdb /usr/local/var/postgres -E utf8                                                       ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then pg_ctl -D /usr/local/var/postgres start && sleep 3 || true                                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then sudo mkdir -p /var/run/postgresql/                                                           ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then sudo ln -s /tmp/.s.PGSQL.5432 /var/run/postgresql/                                           ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then sudo -u travis createuser -s postgres                                                        ; fi

  # PostgreSQL
  - psql --version
  - psql -U postgres -tc 'SHOW server_version'
  - psql -U postgres -c '\conninfo'
  - psql -c "CREATE DATABASE postgresqltest;" -U postgres

  # ODBC - linux
  - if [[ "$TRAVIS_OS_NAME" == linux ]]; then julia --color=yes -e 'using Pkg; pkg"add ODBC"; pkg"precompile"'                             ; fi
  - if [[ "$TRAVIS_OS_NAME" == linux ]]; then julia --color=yes -e 'using ODBC; setupdir=normpath(pathof(ODBC), "..", "..", "test", "setup"); run(`odbcinst -i -s -h -f $(normpath(setupdir, "postgresqltest.odbc.ini"))`)' ; fi

  # linux - MySQL      - 5.6.33
  - if [[ "$TRAVIS_OS_NAME" == linux ]]; then mysql -e 'show variables like "socket";' -uroot                                              ; fi

  # osx   - MySQL      - 5.7.21
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then brew update-reset                                                                            ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then brew install mysql                                                                           ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then brew services start mysql                                                                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then sudo chown -R _mysql:_mysql /usr/local/opt/mysql/                                            ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then mysql.server start                                                                           ; fi
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then sleep 0.1                                                                                    ; fi

  # MySQL
  - mysql -e 'CREATE DATABASE mysqltest;' -uroot
  - mysql -e 'GRANT ALL PRIVILEGES ON mysqltest.* TO "root"@"localhost"' -uroot
  - mysql --version

script:
  - julia --color=yes --project --handle-signals=no -e 'using Pkg; pkg"instantiate"; pkg"precompile"; Pkg.test(coverage=true)'

after_success:
  - if [[ "$TRAVIS_OS_NAME" == linux && "$TRAVIS_JULIA_VERSION" == 1.1 ]] ; then julia --color=yes --project=. -e 'using Pkg;
                                                                                                                   Pkg.add("Coverage");
                                                                                                                   using Coverage;
                                                                                                                   Codecov.submit(process_folder())' ; fi
